org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=easiernetherite
mod_name=Easier Netherite
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.withrage.easiernetherite
mod_authors=JustErikSK, With Rage Studios
mod_description=Make gathering Netherite a bit easier for yourself!